### ISSUE TITLE
Fan wiring

### ISSUE THREAD

**Issue by leeb81** [willblev/UDS_ATC#3]
Hi. I'm new to Arduino and esp8266. I've build a couple of simpler projects both standalone and with blynk, but I'm struggling with the fan wiring.

I see you have used a 4 wire fan for the pwm, but cannot see where you have wired the tacho pin to or if it is wired at all.

**Comment by willblev** [comment]
Hi leeb81,

No worries- I'm no expert either- I will try to help clear up the ambiguity. I meant to upload a schematic of the project when I finished, but I never got around to it... sorry!

 You're correct to guess that I don't wire the tach pin. I only tell the fan the relative speed I want via the PWM pin, and then I assume that it's spinning at the speed I asked for. If the fan stalled or burned out, I'd currently have no way of knowing. 

Best of luck!

**Comment by leeb81** [comment]
Thanks for the quick reply. That clears it up nicely, I can work all the rest out from the code. Now I just have to wait for the max6675s that I ordered to turn up, and I can finally sit indoors while the BBQ does its business.
